### ISSUE TITLE
Updated libjabra.so?

### ISSUE THREAD

**Issue by shadow974** [gnaudio/jabra-browser-integration#23]
is there a chance to get the Linux-SDK-Binary updated?
The current source can not be compiled against the old library.

**Comment by extmchristensen** [comment]
There is no plans for official Linux support now and I have not tried compiling for Linux. Maybe it works if you take the newly released native sdk library so file from jabra developer zone and update that.

If you explain your use case better I can forward your request to our PM.

**Comment by shadow974** [comment]
Im trying to compile the ChromHost binary under Linux. After fixxing a lot of "case-sensitive filesystem" errors the linker fails with errors like:
``HeadsetIntegrationService.cpp:(.text+0xc049): undefined reference to `Jabra_GetSupportedFeatures'``

The windows SDK-Library libjabra.dll has those functions, the linux libjabra.so does not.

I got the ChromeHost binary compiled if i use the branch _fix0.51installer_. It seems that  the codebase does not use those "new" functions from the library.

I got everything working under linux. 3CX WebClient, Jabra Headset-Plugin for Chrome and ChromeHost. Everything works fine...

**Comment by extmchristensen** [comment]
This is because the code use the newest version of the native sdk (libjabra) from. The native sdk can be downloaded from "https://developer.jabra.com/site/global/home/index.gsp" but apparently the linux version has not been updated ... yet.

**Comment by shadow974** [comment]
> but apparently the linux version has not been updated ... yet.
and thats why i opened this issue.

Why is this binary not open-sourced? Let the community help with supporting the linux-version..

**Comment by extmchristensen** [comment]
Unfortunately,  nothing I can do with the the native sdk being closed sourced. You can write to the developer zone at  "https://developer.jabra.com/site/global/home/index.gsp" and ask for it to be opened up if you want to send the request to the right persons. 

But after the linux version of the native sdk is released I can try to see if I can update the .so file so it will compile. For this it will be helpful if you first make a PR with the other "case-sensitive filesystem" errors fixes you have made.

**Comment by frederiksen** [comment]
Some month ago - @mortflem tried to build a Linux host - and he was successful in doing it - so it can be done.
