### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by vegarda** [gnaudio/jabra-browser-integration#25]
Hello,

I'm building a browser application with WebRTC softphone and I want to use this library to integrate Jabra headset functionality like answer and hangup.

I'm using npm for managing all my packages for compiling/bundling and other web frameworks and libraries.

It would be great if you could upload this library to npm so I don't have to manually update when you update.

Thank you

**Comment by extmchristensen** [comment]
Is it a normal page hosted in a chrome browser you are developing ? (Or is it an embedded browser application using electron or similar) ?

**Comment by vegarda** [comment]
It's an Angular-based single-page application for chrome (and edge, firefox)

**Comment by extmchristensen** [comment]
ok. I can see how an npm or bower package could be useful for this. I will ask our PM to add this to our backlog.

**Comment by extmchristensen** [comment]
Happy to report that a beta npm package called @[gnaudio/jabra-browser-integration](https://www.npmjs.com/package/@gnaudio/jabra-browser-integration) for the upcomming v3.0 release has now been released.
