### ISSUE TITLE
setBusylight() with Jabra 9465

### ISSUE THREAD

**Issue by markusoe** [gnaudio/jabra-browser-integration#33]
Hello! I tried using the jabra JS library to add some functionality to our internal app.

Functions like ring() or onHook/offHook() work fine, however I cannot get setBusyLight() to work on its own. 

When calling the function, I get the following error in the console:

Uncaught (in promise) CommandError: Command setbusylight failed with error  message setbusylight and details: [["returnErrorCode",3],["errormsg","setbusylight failed"],["command","setbusylight"],{"deviceID":"0"},{"activeDevice":true}]
    at initState.eventCallback (http://domain/jabra.browser.integration-2.0.js:405:53

Is is possible to make this work with a Jabra 9485 base station?

**Comment by extmchristensen** [comment]
Hi markusoe,
THe error 3 means "not supproted". Not sure about the Jabra 9485 (are you sure the name is correct?) but the 9400 series appears to need an external attached busy indicator to support busy light. Do you have one attached?

**Comment by markusoe** [comment]
Jabra Pro 9465, sorry. The busylight is attached and works fine during a call. Firmware is at version 4.6.0, so almost current. Only the specific setBusyLight() command does not seem to work.

**Comment by extmchristensen** [comment]
I have checked with the firmware folks at Jabra and the 9400 devices does not support changing external busylight (properly due to device missing it's own busylight indicator). Try a device with internal busy light indicator.
