### ISSUE TITLE
Jabra Busylight

### ISSUE THREAD

**Issue by vegarda** [gnaudio/jabra-browser-integration#35]
Does the  Jabra Browser Integration work with the [Jabra Busylight](https://www.jabra.com/supportpages/jabra-busylight)?  

If not, do you have any plans to implement it?

**Comment by frederiksen** [comment]
This device can be attached to some of our devices (read the FAQ - Can I use the Jabra Busylight with all Jabra products?). It should be working with these devices. Please respond if you have any issues.
