### ISSUE TITLE
Cross-extensions communication

### ISSUE THREAD

**Issue by JKoehren** [gnaudio/jabra-browser-integration#40]
Hi,
I need to use the jabra-browser-integration extension with another chrome extension.

I saw on this [chrome doc](https://developer.chrome.com/extensions/messaging#external) that the listening extension must use `runtime.onMessageExternal` but jabra extension doesn't support it. 
I would like to know if the cross-extension functionality will be planned or if another way exists (without a personal fork of the jabra extension).

Thanks you.

**Comment by extmchristensen** [comment]
Currently no plans, but if you can contribute a PR (that does not require additional permissions for our extension) + a test case, the functionality can be added.

**Comment by extmchristensen** [comment]
Closing this as not PR has been contributed.
