### ISSUE TITLE
Chrome OS Support?

### ISSUE THREAD

**Issue by michaelsolla** [gnaudio/jabra-browser-integration#41]
So could be merged in with the question for #37 but any chance of Chrome OS support down the road?

**Comment by extmchristensen** [comment]
ChromeOS support is possible - If you post your use case (along with number of seats) we will include it in our discussions/planning.

**Comment by jabra-slawaetz** [comment]
Please note that ChromeOS is now supported through the new JavaScript call-control library as described on the Jabra Developer Zone ( https://developer.jabra.com/site/global/software/integration-components/javascript/index.gsp )
