### ISSUE TITLE
Headset publishes only Mute or only Unmute events

### ISSUE THREAD

**Issue by DurkoMatko** [gnaudio/jabra-browser-integration#42]
**Issue**: My headset is in offHook state. I repeatedly click microphone button and expect to receive mute -> unmute event sequences. Instead I get only mute events and unmutes are ignored (but the device gets correctly unmuted and light indicator on the device is also always in the right state). I also managed to get to a situation where situation was opposite and only unmute events were received.

![image](https://user-images.githubusercontent.com/8964422/63005067-1049b980-be7c-11e9-8350-f95d9f3c5fb9.png)

**Devices**: JABRA Evolve Link, JABRA Handset 450 
I can replicate this with both mentioned devices in my app as well as with the hosted version of this repo (https://gnaudio.github.io/jabra-browser-integration/beta/test/)

**Possible source of the issue**: My Chrome extension says it's incomplete and needs update but updating or removing & adding it again doesn't help either.

![image](https://user-images.githubusercontent.com/8964422/63006228-63bd0700-be7e-11e9-836b-41f5c425be02.png)

**Comment by frederiksen** [comment]
Hi @DurkoMatko. Using the mute-button on a device does not toggle the mute state. It's documented here: https://github.com/gnaudio/jabra-browser-integration#sequence-diagrams

The events are requests, you need to acknowledge these requests.

**Comment by DurkoMatko** [comment]
@frederiksen Oh, my bad. Thanks!

**Comment by NunoCuradoFuze** [comment]
@DurkoMatko By experimenting your hosted version, I noticed that the mute event from device->app is instantly being recognized, by setting the bit value to the right status. Unmuting from device->app afterwards is not giving that feedback, it seems no input event is received. Only muting it again sets the state to unmuted, per console log.
Is that a normal behaviour? Shouldn't the unmute button triggers an input report event that instantly sets the mute bit value to 0 again?
