### ISSUE TITLE
Handling multiple calls

### ISSUE THREAD

**Issue by cdiscla** [gnaudio/jabra-browser-integration#45]
Hello
i would like to handle multiple calls; when they arrive i add the JSSIP session id in an array,
when one of them are terminated, i need to switch from that session id to another
to be able to control it with the Jabra buttons, but i do not know how to map
jabra() with a particular session id. How can i do that?

Thanks in advance and greetings

**Comment by extmchristensen** [comment]
I am not sure I understand. I would need much more details, incl. pseudo code to understand your case entirely. Some of it does sound like generic application code that we can't help you with here and not so much jabra specific. As for using the Jabra buttons to control something,  if you have a capable device like for example Jabra Engage 50, you can take over button control to perform custom actions with MMI and the setMmiFocus call. The [amazon connect example](https://github.com/gnaudio/jabra-browser-integration/blob/master/src/DeveloperSupportBeta/amazonconnectclient/jabra.connect.integration.js) does this by reprogramming the dot-3 and dot-4 buttons to perform calls etc.

**Comment by extmchristensen** [comment]
Closed due to lack of response
