### ISSUE TITLE
Jabra Pro 9450 Command (Green/White Button)

### ISSUE THREAD

**Issue by simonwood0609** [gnaudio/jabra-browser-integration#47]
Sorry - I don't know where else to ask.

Using Jabra Pro 9450.  Currently to switch between PC Audio & Phone Audio, I press this button.

![image](https://user-images.githubusercontent.com/18339962/67918308-e89efd80-fbef-11e9-87a8-d6c8d278a79d.png)

WHITE = PC AUDIO
GREEN = PHONE AUDIO

Does this library have a command call this function?

jabra.offHook() and jabra.onHook() aren't the same / don't achieve that.

**Comment by simonwood0609** [comment]
From the API Test Page, physically pressing the button results in these logs:

Switch from PC Audio to Phone Audio (green light on):
```
event object: {
  "data": {
    "activeDevice": true,
    "buttonInData": false,
    "deviceID": 0,
    "isOffHook": false,
    "ringing": false,
    "translatedInData": 21
  },
  "message": "lineidle"
}
```

Switch from Phone Audio to PC Audio (white light on):
```
event object: {
  "data": {
    "activeDevice": true,
    "buttonInData": true,
    "deviceID": 0,
    "isOffHook": false,
    "ringing": false,
    "translatedInData": 18
  },
  "message": "online"
}
```

**Comment by simonwood0609** [comment]
BUMP

**Comment by simonwood0609** [comment]
?

**Comment by simonwood0609** [comment]
Hello?

**Comment by extmchristensen** [comment]
One of my colleagues will be back to you soon about this.
BTW: What do you mean exactly by "Does this library have a command to press that button?"

**Comment by simonwood0609** [comment]
Thanks for getting back to me.

I'm using that language because I don't know how Jabra names the function which that physical button calls.

I've updated my original comment for readability.

**Comment by jabra-slawaetz** [comment]
I assume you want to toggle the line from your app just as if you pressed the button manually.
This is not immediately available in our API as a discrete operation as far as I can tell.
We will inquire in the development organisation to see if the same effect can be achieved by other means.

**Comment by simonwood0609** [comment]
Hi @jabra-slawaetz - yes please, and thank you!

**Comment by simonwood0609** [comment]
Just following up here.

**Comment by jabra-slawaetz** [comment]
I will ask if any progress on this has been made.

**Comment by jabra-slawaetz** [comment]
We've dug back into the firmware teams, and they confirmed that the key in question can *not* be "pressed" via the APIs.
So the answer is no, I'm afraid.

**Comment by simonwood0609** [comment]
I'm concerned perhaps my message has been lost in translation, or maybe I wasn't clear.

The reason I used the terminology "press the button" is simply because I don't know the name (or fully understand the function).

The button seems to "toggle between PC/Phone Audio".  Sometimes a third orange mode happens but I don't know what triggers it or what it means.

In either case - what is the API function to turn on/off PC and Phone Audio?

**Comment by jabra-slawaetz** [comment]
No sorry, you came through loud and clear.

Engineering has confirmed that there is not way to toggle between PC and Phone audio using an API function.

In other words, a similar behaviour to "pressing the button", but doing so via software.

**Comment by simonwood0609** [comment]
I could be mistaken - but that seems like one of the basic/important functions?

It was available previously before a recent firmware update I think.

Is the restoration of that function on your roadmap?

**Comment by jabra-slawaetz** [comment]
I'm afraid the firmware software team confirmed that the device firmware does not support any API commands triggering the switching.

It would, however, be interesting to learn on your use case for such a feature. Can you provide an outline on when this function would make sense, and what it would provide the user?

We have to say, though, that as the 9450 is a relatively mature product, and has reached end-of-manufacturing, it is unlikely that a firmware with such a feature will be introduced.

**Comment by extmchristensen** [comment]
Closing as requested behavior is not supported by device
