### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by incx512** [gnaudio/jabra-browser-integration#52]
Looking at rolling this out at PGG call centre, currently we use Jabra9450. What versions of Chrome does it not play nice with (we are all win10, ver 76 or thereabouts with Chrome). Are there any known issues with integration when Chrome updates itself?

**Comment by extmchristensen** [comment]
I am not aware of any known problems with recent Chrome versions incl. ver 76 as mentioned.
No known issues with Chrome updating.
When we update the chrome extension itself however, I have heard that some users need to restart their browser.
Nb. If you do experience any issues with your rollout please report them at [Jabra Developer](https://developer.jabra.com/) for fastest response.
