### ISSUE TITLE
Question: Version 3 changelog

### ISSUE THREAD

**Issue by nnew2** [gnaudio/jabra-browser-integration#57]
Hello,

We've been having some issues with unexpected endcalls from the Jabra integration and I stumbled across this https://github.com/gnaudio/jabra-browser-integration/issues/51

In the issue you mention that version 3 was due for early 2020 and contained a lot of bugfixes. Are there any more information on these bug fixes, and when can we expect version 3?

**Comment by extmchristensen** [comment]
Relatively soon.
